name: pytorch_iotest
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.8.10
  - pytorch==1.10.1
  - torchvision==0.11.2
  - torchaudio==0.10.1
  - cudatoolkit=11.3
  - opencv-python
  - matplotlib
  - scipy
  - pandas